//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altostratus.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Altostratus.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversation Categories.
        /// </summary>
        internal static string Configuration_CategoriesHeader {
            get {
                return ResourceManager.GetString("Configuration_CategoriesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversations to show per category: {0}.
        /// </summary>
        internal static string Configuration_ConversationLimitHeader {
            get {
                return ResourceManager.GetString("Configuration_ConversationLimitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged into {0} as {1}.
        /// </summary>
        internal static string Configuration_LoggedInto {
            get {
                return ResourceManager.GetString("Configuration_LoggedInto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string Configuration_Login {
            get {
                return ResourceManager.GetString("Configuration_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        internal static string Configuration_Logoff {
            get {
                return ResourceManager.GetString("Configuration_Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a provider to log in.
        /// </summary>
        internal static string Configuration_NotLoggedIn {
            get {
                return ResourceManager.GetString("Configuration_NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Configuration_PageTitle {
            get {
                return ResourceManager.GetString("Configuration_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Providers.
        /// </summary>
        internal static string Configuration_ProvidersLabel {
            get {
                return ResourceManager.GetString("Configuration_ProvidersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uh-oh.
        /// </summary>
        internal static string Home_NoCategoriesMessage1 {
            get {
                return ResourceManager.GetString("Home_NoCategoriesMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select at least one category in the configuration for stuff to show up here..
        /// </summary>
        internal static string Home_NoCategoriesMessage2 {
            get {
                return ResourceManager.GetString("Home_NoCategoriesMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string Home_OfflineMessage {
            get {
                return ResourceManager.GetString("Home_OfflineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversations.
        /// </summary>
        internal static string Home_PageTitle {
            get {
                return ResourceManager.GetString("Home_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        internal static string Home_ToolbarItem_Configure {
            get {
                return ResourceManager.GetString("Home_ToolbarItem_Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Home_ToolbarItem_Refresh {
            get {
                return ResourceManager.GetString("Home_ToolbarItem_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversation Detail.
        /// </summary>
        internal static string Item_PageTitle {
            get {
                return ResourceManager.GetString("Item_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;em&gt;Sorry, this item has been removed from the local database in favor of newer items.&lt;/em&gt;.
        /// </summary>
        internal static string Item_RemovedMessage {
            get {
                return ResourceManager.GetString("Item_RemovedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login_PageTitle {
            get {
                return ResourceManager.GetString("Login_PageTitle", resourceCulture);
            }
        }
    }
}
